[package]
name = "iot-image-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
image = "0.25.1"
num-complex = "0.4.4"
plotters = "0.3.5"
plotters-backend = "0.3.5"
plotters-bitmap = "0.3.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }

[profile.release]
lto = true
strip = true
opt-level = "z"
